export const mockUser = {
  id: '1',
  name: 'John Doe',
  email: 'john.doe@kingston.ac.uk',
  studentID: 'STU001',
  major: 'Computer Science',
  year: 'Third Year',
  bio: 'Computer Science major passionate about teaching and learning new skills.',
  rating: 4.8,
  skillsOffered: ['Python', 'Web Development', 'Data Analysis'],
  skillsNeeded: ['Spanish', 'Graphic Design'],
  credits: 1250,
  servicesOffered: 12,
  servicesRequested: 8,
  completedExchanges: 6,
  role: 'student',
};

export const adminUser = {
  id: 'admin1',
  name: 'Ali Assi',
  email: 'K2355109@KINGSTON.AC.UK',
  role: 'admin',
  permissions: ['manage_users', 'manage_services', 'view_reports', 'moderate_content'],
};

export const mockServices = [
  {
    id: '1',
    title: 'Python & Data Science Tutoring',
    user: 'Sarah Johnson',
    userId: '2',
    rating: 4.9,
    category: 'Programming',
    description: 'Master Python fundamentals, pandas, and NumPy with hands-on projects using real datasets.',
    credits: 50,
  },
  {
    id: '2',
    title: 'Conversational Spanish for Beginners',
    user: 'Carlos Rodriguez',
    userId: '3',
    rating: 4.9,
    category: 'Languages',
    description: 'Learn to speak Spanish confidently in everyday situations. Focus on pronunciation and real conversations.',
    credits: 80,
  },
  {
    id: '3',
    title: 'Professional Video Editing',
    user: 'Emma Davis',
    userId: '4',
    rating: 4.8,
    category: 'Design',
    description: 'Learn DaVinci Resolve or Premiere Pro — cutting, transitions, color grading, and audio mixing.',
    credits: 55,
  },
  {
    id: '4',
    title: 'Guitar Lessons — Acoustic & Electric',
    user: 'Alex Smith',
    userId: '5',
    rating: 4.7,
    category: 'Music',
    description: 'From chords to fingerpicking to soloing. Beginner to intermediate. Bring your own guitar!',
    credits: 90,
  },
  {
    id: '5',
    title: 'Machine Learning Fundamentals',
    user: 'Michael Chen',
    userId: '6',
    rating: 4.9,
    category: 'Academics',
    description: 'Build and deploy your first ML model. Covers scikit-learn, neural networks, and model evaluation.',
    credits: 90,
  },
  {
    id: '6',
    title: 'UI/UX Design Masterclass',
    user: 'Olivia Brown',
    userId: '7',
    rating: 4.8,
    category: 'Design',
    description: 'Learn Figma, wireframing, prototyping, and user research. Create a complete app design from scratch.',
    credits: 70,
  },
];

export const mockActivities = [
  {
    id: '1',
    user: 'John Doe',
    action: 'offered a service',
    time: '2 hours ago',
    service: 'Python Tutoring',
  },
  {
    id: '2',
    user: 'Jane Smith',
    action: 'completed a skill exchange',
    time: '1 day ago',
    service: 'Spanish Lessons',
  },
  {
    id: '3',
    user: 'Mike Johnson',
    action: 'rated your service',
    time: '2 days ago',
    service: 'Video Editing',
    rating: 5,
  },
];

export const mockReviews = [
  {
    id: '1',
    user: 'John Doe',
    rating: 5,
    text: 'Excellent service! Very professional and knowledgeable.',
    tags: ['Professional', 'Responsive'],
    date: '3 days ago',
  },
  {
    id: '2',
    user: 'Jane Smith',
    rating: 4,
    text: 'Good service, very helpful and patient with my questions.',
    tags: ['Helpful', 'Knowledgeable'],
    date: '5 days ago',
  },
  {
    id: '3',
    user: 'Mike Johnson',
    rating: 5,
    text: 'Amazing experience! Learned so much in just one session.',
    tags: ['Professional', 'Patient'],
    date: '1 week ago',
  },
];

export const mockConversations = [
  {
    id: '1',
    participantName: 'Sarah Johnson',
    participantId: '2',
    lastMessage: 'Thanks! See you tomorrow at 3pm',
    timestamp: '5m ago',
    unread: 2,
    online: true,
  },
  {
    id: '2',
    participantName: 'Carlos Rodriguez',
    participantId: '3',
    lastMessage: 'Sure, let me know when you\'re available',
    timestamp: '1h ago',
    unread: 0,
    online: true,
  },
  {
    id: '3',
    participantName: 'Emma Davis',
    participantId: '4',
    lastMessage: 'Great! I can help with that',
    timestamp: '2h ago',
    unread: 1,
    online: false,
  },
  {
    id: '4',
    participantName: 'Alex Smith',
    participantId: '5',
    lastMessage: 'What time works best for you?',
    timestamp: '1d ago',
    unread: 0,
    online: false,
  },
];

export const mockMessages = [
  {
    id: '1',
    senderId: '2',
    text: 'Hi! I saw your offer for Python tutoring',
    timestamp: '10:30 AM',
  },
  {
    id: '2',
    senderId: '1',
    text: 'Hi Sarah! Yes, I\'m happy to help. What topics are you interested in?',
    timestamp: '10:32 AM',
  },
  {
    id: '3',
    senderId: '2',
    text: 'I need help with data structures, especially linked lists and trees',
    timestamp: '10:35 AM',
  },
  {
    id: '4',
    senderId: '1',
    text: 'Perfect! I can definitely help with that. When would you like to meet?',
    timestamp: '10:37 AM',
  },
  {
    id: '5',
    senderId: '2',
    text: 'How about tomorrow at 3pm?',
    timestamp: '10:40 AM',
  },
  {
    id: '6',
    senderId: '1',
    text: 'That works for me! See you then',
    timestamp: '10:42 AM',
  },
  {
    id: '7',
    senderId: '2',
    text: 'Thanks! See you tomorrow at 3pm',
    timestamp: '10:43 AM',
  },
];

export const mockBookings = [
  {
    id: '1',
    title: 'Python Tutoring Session',
    provider: 'Sarah Johnson',
    date: '2024-01-15',
    time: '3:00 PM - 4:30 PM',
    status: 'upcoming',
    location: 'Library Room 204',
    credits: 100,
  },
  {
    id: '2',
    title: 'Spanish Lesson',
    provider: 'Carlos Rodriguez',
    date: '2024-01-18',
    time: '2:00 PM - 3:00 PM',
    status: 'upcoming',
    location: 'Student Center',
    credits: 80,
  },
  {
    id: '3',
    title: 'Video Editing Workshop',
    provider: 'Emma Davis',
    date: '2024-01-12',
    time: '1:00 PM - 2:30 PM',
    status: 'completed',
    location: 'Media Lab',
    credits: 120,
  },
];

export const mockMatches = [
  {
    id: '1',
    name: 'Emily Thompson',
    userId: '8',
    matchScore: 95,
    offeredSkills: ['Spanish', 'Graphic Design'],
    neededSkills: ['Python', 'Web Development'],
    rating: 4.9,
    completedExchanges: 15,
    bio: 'Marketing major looking to learn programming',
  },
  {
    id: '2',
    name: 'David Kim',
    userId: '9',
    matchScore: 88,
    offeredSkills: ['Graphic Design', 'UI/UX Design'],
    neededSkills: ['Web Development', 'JavaScript'],
    rating: 4.7,
    completedExchanges: 12,
    bio: 'Design student interested in web technologies',
  },
  {
    id: '3',
    name: 'Rachel Martinez',
    userId: '10',
    matchScore: 82,
    offeredSkills: ['Spanish', 'Translation'],
    neededSkills: ['Data Analysis', 'Python'],
    rating: 4.8,
    completedExchanges: 10,
    bio: 'Languages major exploring data science',
  },
];

export const mockNotifications = [
  {
    id: '1',
    type: 'message',
    title: 'New message from Sarah Johnson',
    description: 'Thanks! See you tomorrow at 3pm',
    timestamp: '5m ago',
    read: false,
  },
  {
    id: '2',
    type: 'booking',
    title: 'Booking Confirmed',
    description: 'Your session with Carlos Rodriguez is confirmed for Jan 18',
    timestamp: '1h ago',
    read: false,
  },
  {
    id: '3',
    type: 'match',
    title: 'New Skill Match Found!',
    description: 'Emily Thompson (95% match) might be perfect for you',
    timestamp: '3h ago',
    read: true,
  },
  {
    id: '4',
    type: 'review',
    title: 'New Review Received',
    description: 'Mike Johnson gave you 5 stars',
    timestamp: '1d ago',
    read: true,
  },
  {
    id: '5',
    type: 'request',
    title: 'Service Request',
    description: 'Alex Smith wants to book your Python tutoring service',
    timestamp: '2d ago',
    read: true,
  },
  {
    id: '6',
    type: 'reminder',
    title: 'Upcoming Session',
    description: 'You have a session with Sarah Johnson tomorrow at 3pm',
    timestamp: '1d ago',
    read: true,
  },
  {
    id: '7',
    type: 'credits',
    title: 'Credits Earned',
    description: 'You earned 120 credits from your last exchange',
    timestamp: '3d ago',
    read: true,
  },
];

export const mockPortfolio = [
  {
    id: '1',
    title: 'E-commerce Website',
    category: 'Web Development',
    description: 'Full-stack e-commerce platform built with React and Node.js',
    imageUrl: null,
    likes: 24,
    views: 156,
    date: '2023-12-10',
  },
  {
    id: '2',
    title: 'Data Analysis Dashboard',
    category: 'Programming',
    description: 'Interactive dashboard for visualizing sales data using Python and Plotly',
    imageUrl: null,
    likes: 18,
    views: 98,
    date: '2023-11-25',
  },
  {
    id: '3',
    title: 'Mobile App UI Design',
    category: 'Design',
    description: 'Modern UI design for a fitness tracking mobile application',
    imageUrl: null,
    likes: 32,
    views: 201,
    date: '2023-11-05',
  },
  {
    id: '4',
    title: 'Machine Learning Model',
    category: 'Programming',
    description: 'Predictive model for student performance using scikit-learn',
    imageUrl: null,
    likes: 15,
    views: 87,
    date: '2023-10-20',
  },
];
